name: Docker Image CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Unit test
      run: auto/test
    - name: Build the Docker image
      run: auto/build
